sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: { sky.alioss.endpoint }
    access-key-id: { sky.alioss.access-key-id }
    access-key-secret: { sky.alioss.access-key-secret }
    bucket-name: { sky.alioss.bucket-name }
  # 配置redis的数据源
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  # 设置wechat的账号信息
  wechat:
    appid:
    secret: